### PR TITLE
Update Inferno dependency.

### PR DESCRIPTION
**Pull request by jails**
Update examples to work with the last inferno.

### CODE REVIEW

**Comment by trueadm** [comment]
@jails thank you for this :)

**Comment by trueadm** [comment]
@jails I can't seem to get it deployed via ` gulp deploy`. ```[07:00:32] Using gulpfile ~/vdom-benchmark-inferno/gulpfile.js
[07:00:32] Starting 'scripts'...
[07:00:32] Starting 'html'...
[07:00:32] Finished 'html' after 12 ms
[07:00:32] Finished 'scripts' after 436 ms
[07:00:32] Starting 'default'...
[07:00:32] Finished 'default' after 38 μs
[07:00:32] Starting 'deploy'...
[07:00:32] [gulp-gh-pages]: Cloning repo
[07:00:32] [gulp-gh-pages]: Checkout branch `gh-pages`
[07:00:32] [gulp-gh-pages]: Copying files to repository
[07:00:32] [gulp-gh-pages]: No files have changed.```

@localvoid @jails I've added you both to the repo so you can take a look if you think you can deploy it?

**Comment by localvoid** [comment]
Done.

**Comment by trueadm** [comment]
@localvoid  thanks :)

**Pull request merged**
